### ISSUE TITLE
const __1 = require("../..") 

### ISSUE THREAD

**Issue by igornoriaqui** [bluelovers/cjk-convert#1]
missing this import

/node_modules/cjk-conv/lib/zh/table/list.js
const __1 = require("../..");

//__1.default..
.concat(arr.map(w(__1.default.cjk2zht)))
        // @ts-ignore
        .concat(arr.map(w(__1.default.cn2tw)))
        // @ts-ignore
        .concat(arr.map(w(__1.default.cjk2zhs)))
        // @ts-ignore
        .concat(arr.map(w(__1.default.cjk2jp)))

**Comment by bluelovers** [comment]
@igornoriaqui 
xd already hotfix

https://github.com/bluelovers/cjk-convert/commit/e34e5ff7042e383a2b2f879fa6eb8f5fb7099b32
