### ISSUE TITLE
Question about the tables

### ISSUE THREAD

**Issue by LiMinggang** [bluelovers/cjk-convert#2]
@bluelovers did you have some reference on the convert tables? I did not find any official mapping tables of traditional/simplified Chinese or Japanese Kanji. Yours is different from the one shown on Wikipedia(also different from the one in MadEdit).

**Comment by bluelovers** [comment]
https://ja.wiktionary.org/wiki/Wiktionary:%E3%83%A1%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8

https://zh.wiktionary.org/wiki/Wiktionary:%E9%A6%96%E9%A1%B5

**Comment by LiMinggang** [comment]
I'm working on the issue you opened now and fixed a bug in converting Chinese. I found some duplicated chars in the table as below.
		"亘": "亘",
		"亙": "亙",
		"伙": "伙",
		"佑": "佑",

What's the purpose or just by mistake.

**Comment by bluelovers** [comment]
喔 這些 是為了防止被轉換 所以才特地加上去 讓他覆寫我所使用的基底 table

**Comment by LiMinggang** [comment]
我还发现BIG5好像对中文里面四字节的支持的不好，好像很多方案都因为公司倒闭而废弃了，只有香港在持续定标准，比如BIG5HKSCS。现在有什么编辑器支持这种编码吗？

**Comment by bluelovers** [comment]
不太清楚呢 一直以來都是用 madedit

================

對了 關於 table 我是用 chinese_convert + wikipedia 然後再加上 我自己的修正對應表

然後因為我是以小說翻譯為樣本來檢查的
所以可能還有些少見錯誤對應沒有檢查修正到

一對多的部分 則是有些會以轉換後 需要修改的工作量多寡 來選擇

https://github.com/bluelovers/cjk-convert/blob/master/lib/zh/convert/table_plus.ts

https://github.com/bluelovers/cjk-convert/blob/master/lib/zh/convert/table.ts

https://github.com/bluelovers/cjk-convert/blob/master/lib/zh/convert/min.ts

================

日文部分
------------

https://github.com/bluelovers/cjk-convert/blob/master/lib/jp/table.ts

https://github.com/bluelovers/cjk-convert/tree/master/lib/jp

底下的
teachKanjiComparison.cache.json
teachKanjiComparison.cache2.json
teachKanjiComparison.json
teachKanjiComparison.safe.json

===================

wikipedia (有部分需要修改對應，不適合直接使用)
---------
https://github.com/bluelovers/cjk-convert/blob/master/lib/zh/convert/wikipedia.ts

chinese_convert (有不少錯誤 但與其他這類比較上 比較適合我修改)
-------

https://github.com/ccckmit/chinese_convert/blob/master/cn2tw.js
https://github.com/ccckmit/chinese_convert/blob/master/tw2cn.js

**Comment by LiMinggang** [comment]
我基本会参照你的表，去掉那些一样的，然后再加入一些MadEdit上的对标点的转换。就是不知道是否有必要内置（embed）对BIG5HKCSC的支持
