### ISSUE TITLE
請問如何添加自定義的轉換?

### ISSUE THREAD

**Issue by flier268** [bluelovers/cjk-convert#3]
因為使用cn2tw(cn)後，發現轉出來的會出現
```
右擊地麵
所有堅硬方塊的表麵均可
```
這樣的東西，或者因為有些比較偏門的東西需要轉換，所以想要加入自定義的詞，請問有什麼方法嗎？

**Comment by bluelovers** [comment]
使用 `cn2tw_min` 

```ts
import { tw2cn_min, cn2tw_min } from '@lazy-cjk/zh-convert/min';

```

或者 在 參數內傳遞 `table`

```ts
import { tw2cn, cn2tw } from '@lazy-cjk/zh-convert';

cn2tw('右擊地面', {
table: {
'面': '面',
},
})
```

或者 使用忽略功能

https://github.com/bluelovers/cjk-convert/blob/50637b8fd5a9559729b789bc48d987020277b54b/README.md#zhconvert

或者使用 novel-segment 模組的 詞語分析之後 在轉繁的功能
https://github.com/bluelovers/ws-segment/tree/master/packages/novel-segment

**Comment by flier268** [comment]
請問是這樣用嗎？感覺好像怪怪的
```typescript
var convert = (str) => {
    return cn2tw_min(segment.doSegment(str, { simple: true }).join(''));
};
```

**Comment by bluelovers** [comment]
```ts
ret = segment.doSegment(text);
let output_text = segment.stringify(ret); // <== 這各會自動處理 doSegment 的結果 不論你用的是什麼參數選項
let output_text2 = cn2tw_min(output_text);
```

參考

https://github.com/bluelovers/ws-segment/blob/e10060feaef6c5ceb8e30dcaa317170cba4b648b/packages/novel-segment-cli/index.ts#L80

https://github.com/bluelovers/ws-segment/blob/e10060feaef6c5ceb8e30dcaa317170cba4b648b/packages/novel-segment/test/demo.cache.ts#L130
