### ISSUE TITLE
Uncaught ReferenceError: lodashEs is not defined

### ISSUE THREAD

**Issue by elpwc** [bluelovers/cjk-convert#4]
在 Svelte 内使用时，在网页载入阶段出现了这样的错误。

**Comment by bluelovers** [comment]
> 在 Svelte 内使用时，在网页载入阶段出现了这样的错误。

安裝 `lodash-es` 試試

**Comment by elpwc** [comment]
谢谢~ 这个问题解决了
又出现了 `exports is not defined` 的问题，估计是这边 babel 配置的问题，我再去看看
